{{- if .Values.perfanaGrafanaSync.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: perfana-grafana-sync
  labels:
    app: perfana-grafana-sync
    chart: {{ include "perfana.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.perfanaGrafanaSync.replicaCount }}
  selector:
    matchLabels:
      app: perfana-grafana-sync
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: perfana-grafana-sync
        release: {{ .Release.Name }}
        {{- with .Values.perfanaGrafanaSync.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- if .Values.perfanaGrafanaSync.annotations }}
      annotations: {{ toYaml .Values.perfanaGrafanaSync.annotations | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.perfanaGrafanaSync.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.perfanaGrafanaSync.serviceAccount.name }}
      {{- end}}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.securityContext }}
      securityContext:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: perfana-grafana-sync
          image: "{{ .Values.perfanaGrafanaSync.image.repository }}:{{ .Values.perfanaGrafanaSync.image.tag }}"
          imagePullPolicy: {{ .Values.perfanaGrafanaSync.image.pullPolicy }}
          {{- with .Values.perfanaGrafanaSync.command }}
          command:
          {{ toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.perfanaGrafanaSync.args }}
          args:
          {{ toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.containerSecurityContext }}
          securityContext:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
          {{- range $key, $value := .Values.perfanaGrafanaSync.extraEnvSecrets }}
          - name: {{ $key }}
            valueFrom:
              secretKeyRef:
                name: {{ $value.name }}
                key: {{ $value.key }}
          {{- end }}
          {{- range $key, $value := .Values.perfanaGrafanaSync.env }}
          - name: {{ $key }}
            value: '{{ $value }}'
          {{- end }}
          {{- range .Values.perfanaGrafanaSync.envFromSecrets }}
          {{print "- " (. | toYaml | nindent 12 | trim) }}
          {{- end }}
          resources:
{{ toYaml .Values.perfanaGrafanaSync.resources | indent 12 }}
          volumeMounts:
          {{- if .Values.perfanaGrafanaSync.volumeMounts }}
             {{- toYaml .Values.perfanaGrafanaSync.volumeMounts | nindent 10 }}
          {{- end }}
      volumes:
      {{- if .Values.perfanaGrafanaSync.volumes }}
         {{- toYaml .Values.perfanaGrafanaSync.volumes | nindent 6 }}
      {{- end }}
    {{- with .Values.perfanaGrafanaSync.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.perfanaGrafanaSync.topologySpreadConstraints }}
      topologySpreadConstraints:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.perfanaGrafanaSync.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.perfanaGrafanaSync.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end}}
