{{- if .Values.perfanaReport.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: perfana-report
  labels:
    app: perfana-report
    chart: {{ include "perfana.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.perfanaReport.replicaCount }}
  selector:
    matchLabels:
      app: perfana-report
      release: {{ .Release.Name }}
  strategy:
    type: {{ .Values.perfanaReport.deploymentStrategy }}
  {{- if ne .Values.perfanaReport.deploymentStrategy "RollingUpdate" }}
    rollingUpdate: null
  {{- end }}
  template:
    metadata:
      labels:
        app: perfana-report
        release: {{ .Release.Name }}
        {{- with .Values.perfanaReport.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- if .Values.perfanaReport.annotations }}
      annotations: {{ toYaml .Values.perfanaReport.annotations | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.perfanaReport.serviceAccount.enabled }}
      serviceAccountName: {{ .Values.perfanaReport.serviceAccount.name }}
      {{- end}}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.securityContext }}
      securityContext:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: perfana-report
          image: "{{ .Values.perfanaReport.image.repository }}:{{ .Values.perfanaReport.image.tag }}"
          imagePullPolicy: {{ .Values.perfanaReport.image.pullPolicy }}
          {{- with .Values.perfanaReport.command }}
          command:
          {{ toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.perfanaReport.args }}
          args:
          {{ toYaml . | nindent 10 }}
          {{- end }}
          {{- with .Values.containerSecurityContext }}
          securityContext:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: {{ .Values.perfanaReport.service.targetPort }}
              containerPort: {{ .Values.perfanaReport.service.port }}
              protocol: TCP
          livenessProbe:
            failureThreshold: 8
            httpGet:
              path: /health/live
              port: {{ .Values.perfanaReport.service.port }}
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health/ready
              port: {{ .Values.perfanaReport.service.port }}
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5
          env:
          {{- range $key, $value := .Values.perfanaReport.extraEnvSecrets }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $value.name }}
                  key: {{ $value.key }}
          {{- end }}
          {{- range $key, $value := .Values.perfanaReport.env }}
            - name: {{ $key }}
              value: '{{ $value }}'
          {{- end }}
          resources:
{{ toYaml .Values.perfanaReport.resources | indent 12 }}
          volumeMounts:
          {{- if .Values.perfanaReport.volumeMounts }}
             {{- toYaml .Values.perfanaReport.volumeMounts | nindent 10 }}
          {{- end }}
      volumes:
      {{- if .Values.perfanaReport.volumes }}
         {{- toYaml .Values.perfanaReport.volumes | nindent 6 }}
      {{- end }}
    {{- with .Values.perfanaReport.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.perfanaReport.topologySpreadConstraints }}
      topologySpreadConstraints:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.perfanaReport.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.perfanaReport.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end }}
